PX4/NuttX branch test: master
NuttX:
 - https://github.com/PX4-NuttX/nuttx/tree/master
 - https://github.com/PX4-NuttX/nuttx/commit/e2ce8d5169445eff770c5d6272aff2790c2ca53e

Changes from PX4/NuttX (https://github.com/PX4/NuttX/commit/fdf1837077104e80912a2c46ff159fdacc8b06f9) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX/compare/fdf1837077104e80912a2c46ff159fdacc8b06f9...e2ce8d5169445eff770c5d6272aff2790c2ca53e

e2ce8d5169 (HEAD, origin/master) Fix a typo in Kconfig description
2ff43fb8a8 Run files modified by PR239 through nxstyle.
d5ea46c610 boards/sim: Update README.txt to inform about the xhost command.
e6c67bdd78 arch/sim: Drive up_x11update by work to simplify up_idle.
14a82f40d2 arch/sim: Make eventloop as an internal variable to simplify up_idle.
28d7061550 boards: stm32f4discovery: Modify a default path to a romfs image because the stm32f4discovery directory has been moved from configs/ to boards/arm/stm32/
c4c0d05891 arch/arm/src/imxrt; Adds clock config logic and Kconfig menus for FLEXIO on IMXRT
3c0b49448a Network Loopback Driver:  A configuration option to control packet size.
2af17da334 boards/sim:  Add a TCP loopback test.
ac4e6618bb arch/mips: Clear the software interrupt through a common function implemented in the chip specific code.

Apps:
 - https://github.com/PX4/NuttX-apps/tree/master
 - https://github.com/PX4/NuttX-apps/commit/44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

Changes from PX4/NuttX-apps (https://github.com/PX4/NuttX-apps/commit/91b6ad6a0d00ac107088b18588cd54d40e3cb796) in current PX4/master (0d36e5094b4655c960846d481f62361d40cf1d9f)
https://github.com/PX4/NuttX-apps/compare/91b6ad6a0d00ac107088b18588cd54d40e3cb796...44b8c9c5aa8f2eeb1e742c6a89f9530258fa5b28

44b8c9c5 (HEAD -> master, origin/master) apps/examples/tcpblaster:  Fix compile errors in loopback mode.
539d0854 examples: elf: Fix warnings when compiled for RISC-V 64bit
779197c6 Ensure all source code end with one and only one newline
4a13a089 testing/smp: Replace up_cpu_index with sched_getcpu
d2e1c8a4 apps/wireless/gs2200m/gs2200m_main.c:  Eliminate a warning
c8dbd59e netutils/telnetd/telnetd_daemon.c: Avoid a warning if CONFIG_NET_SOCKOPTS=n
d2522e28 apps/netutils/telnetd:  Fix undefined reference to setsockopt.
f14aead5 Shouldn't use local readline in telnet
960a92c6 (origin/master_nxp_drone_boards) Make SO_REUSEADDR not mandatory in netlib
a5dff52a Change unimplemented requests behaviour in gs2200m